from app.schemas.ontology import ClassDefinition, FieldDefinition, RelationDefinition


ONTOLOGY_CLASSES: dict[str, ClassDefinition] = {
    "Project": ClassDefinition(
        class_name="Project",
        label="项目",
        description="用于承载团队和任务的项目对象",
        table_name="project",
        display_field="name",
        fields=[
            FieldDefinition(name="name", label="项目名称", data_type="string", required=True, placeholder="请输入项目名称"),
            FieldDefinition(name="description", label="项目描述", data_type="text", required=False),
            FieldDefinition(
                name="status",
                label="项目状态",
                data_type="enum",
                required=True,
                enum_options=["planning", "active", "completed", "archived"],
            ),
            FieldDefinition(name="start_date", label="开始日期", data_type="date", required=False),
            FieldDefinition(name="end_date", label="结束日期", data_type="date", required=False),
        ],
        relations=[],
    ),
    "Team": ClassDefinition(
        class_name="Team",
        label="团队",
        description="归属于项目的团队对象",
        table_name="team",
        display_field="name",
        fields=[
            FieldDefinition(name="name", label="团队名称", data_type="string", required=True, placeholder="请输入团队名称"),
            FieldDefinition(
                name="project_id",
                label="所属项目",
                data_type="relation",
                required=True,
                relation_target="Project",
            ),
            FieldDefinition(
                name="leader_developer_id",
                label="团队负责人",
                data_type="relation",
                required=False,
                relation_target="Developer",
            ),
            FieldDefinition(name="description", label="团队描述", data_type="text", required=False),
        ],
        relations=[
            RelationDefinition(
                name="project",
                relation_type="TEAM_BELONGS_TO_PROJECT",
                source_class="Team",
                target_class="Project",
                direction="outgoing",
                source_field="project_id",
                target_field="id",
            ),
            RelationDefinition(
                name="leader",
                relation_type="TEAM_LED_BY_DEVELOPER",
                source_class="Team",
                target_class="Developer",
                direction="outgoing",
                source_field="leader_developer_id",
                target_field="id",
            ),
        ],
    ),
    "Developer": ClassDefinition(
        class_name="Developer",
        label="开发者",
        description="团队成员对象",
        table_name="developer",
        display_field="name",
        fields=[
            FieldDefinition(name="name", label="姓名", data_type="string", required=True, placeholder="请输入开发者姓名"),
            FieldDefinition(name="email", label="邮箱", data_type="string", required=False),
            FieldDefinition(name="role", label="角色", data_type="string", required=True, placeholder="如 backend/frontend"),
            FieldDefinition(name="team_id", label="所属团队", data_type="relation", required=False, relation_target="Team"),
            FieldDefinition(name="skill_tags", label="技能标签", data_type="json_string_array", required=False),
        ],
        relations=[
            RelationDefinition(
                name="team",
                relation_type="DEVELOPER_MEMBER_OF_TEAM",
                source_class="Developer",
                target_class="Team",
                direction="outgoing",
                source_field="team_id",
                target_field="id",
            )
        ],
    ),
    "Task": ClassDefinition(
        class_name="Task",
        label="任务",
        description="归属项目并可指派给开发者的任务对象",
        table_name="task",
        display_field="title",
        fields=[
            FieldDefinition(name="title", label="任务标题", data_type="string", required=True, placeholder="请输入任务标题"),
            FieldDefinition(name="description", label="任务描述", data_type="text", required=False),
            FieldDefinition(name="project_id", label="所属项目", data_type="relation", required=True, relation_target="Project"),
            FieldDefinition(
                name="assignee_developer_id",
                label="指派给",
                data_type="relation",
                required=False,
                relation_target="Developer",
            ),
            FieldDefinition(
                name="status",
                label="状态",
                data_type="enum",
                required=True,
                enum_options=["todo", "doing", "done", "blocked"],
            ),
            FieldDefinition(
                name="priority",
                label="优先级",
                data_type="enum",
                required=True,
                enum_options=["low", "medium", "high"],
            ),
            FieldDefinition(name="estimated_hours", label="预估工时", data_type="number", required=False),
        ],
        relations=[
            RelationDefinition(
                name="project",
                relation_type="TASK_BELONGS_TO_PROJECT",
                source_class="Task",
                target_class="Project",
                direction="outgoing",
                source_field="project_id",
                target_field="id",
            ),
            RelationDefinition(
                name="assignee",
                relation_type="TASK_ASSIGNED_TO_DEVELOPER",
                source_class="Task",
                target_class="Developer",
                direction="outgoing",
                source_field="assignee_developer_id",
                target_field="id",
            ),
        ],
    ),
}
